[profile.release]
panic = 'unwind'

# SBP-M1 review: you can use 'pallets/*'
[workspace]
members = [
    'node',
    'pallets/keystore',
    'pallets/trust',
    'pallets/signal',
    'pallets/identity',
    'runtime',
]
